name: verify
on:
  push:
    branches:
      - main
jobs:
  gittuf-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.21'
      - uses: gittuf/gittuf-installer@main
        with:
          gittuf-version: 'main'
      - run: |
          # Temporarily testing verification with ourselves
          gittuf clone https://github.com/${{ github.repository }}
          cd gittuf-delegation
          gittuf verify-ref -f main
